name: jotrockenmitlocken
description: "Find out sth. interesting about me."
homepage: https://jonasheinle.de

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.3.5

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.1"

dependencies:
  flutter:
    sdk: flutter
  jotrockenmitlockenrepo:
    path: external/jotrockenmitlockenrepo
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^14.8.1
  font_awesome_flutter: any
dev_dependencies:
  mockito: ^5.4.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/barbell.png"
  min_sdk_android: 21
  web:
    generate: true

  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Pages/AboutMe/
    - assets/images/Pages/AboutMe/Bewerbungsbilder/
    - assets/images/Pages/Data/
    - assets/images/Pages/Error/
    - assets/images/Pages/Blog/
    - assets/images/Pages/Blog/VulkanRenderer/
    - assets/images/cats/
    - assets/images/aiBlog/
    - assets/images/books/
    - assets/documents/
    - assets/documents/footer/
    - assets/documents/blog/
    - assets/documents/books/
    - assets/documents/games/
    - assets/documents/thesis/
    - assets/documents/cv/
    - assets/data/
    - assets/settings/
    - assets/settings/user_settings/

fonts:
  - family: Montserrat
    fonts:
      - asset: static/Montserrat-Thin.ttf
      - asset: static/Montserrat-ExtraLight.ttf
      - asset: static/Montserrat-Light.ttf
      - asset: static/Montserrat-Regular.ttf
      - asset: static/Montserrat-Medium.ttf
      - asset: static/Montserrat-SemiBold.ttf
      - asset: static/Montserrat-Bold.ttf
      - asset: static/Montserrat-ExtraBold.ttf
      - asset: static/Montserrat-Black.ttf
      - asset: static/Montserrat-ThinItalic.ttf
        style: italic
      - asset: static/Montserrat-ExtraLightItalic.ttf
        style: italic
      - asset: static/Montserrat-LightItalic.ttf
        style: italic
      - asset: static/Montserrat-Italic.ttf
        style: italic
      - asset: static/Montserrat-MediumItalic.ttf
        style: italic
      - asset: static/Montserrat-SemiBoldItalic.ttf
        style: italic
      - asset: static/Montserrat-BoldItalic.ttf
        style: italic
      - asset: static/Montserrat-ExtraBoldItalic.ttf
        style: italic
      - asset: static/Montserrat-BlackItalic.ttf
        style: italic
  - family: Roboto
    fonts:
      - asset: Roboto-Black.ttf
      - asset: Roboto-BlackItalic.ttf
        style: italic
      - asset: Roboto-Bold.ttf
        weight: 700
      - asset: Roboto-BoldItalic.ttf
        style: italic
        weight: 700
      - asset: Roboto-Italic.ttf
        style: italic
      - asset: Roboto-Light.ttf
      - asset: Roboto-LightItalic.ttf
        style: italic
      - asset: Roboto-Medium.ttf
        weight: 400
      - asset: Roboto-MediumItalic.ttf
        weight: 400
        style: italic
      - asset: Roboto-Regular.ttf
      - asset: Roboto-Thin.ttf
        weight: 200
      - asset: Roboto-ThinItalic.ttf
        weight: 200
        style: italic
